<%-- pace --%>
<script type="text/javascript" src="${ctx}/static/libs/pace/pace.min.js"></script>
<%-- form --%>
<script type="text/javascript" src="${ctx}/static/libs/jquery-plugin/jquery.form.js"></script>
<%-- slimscroll --%>
<script type="text/javascript" src="${ctx}/static/libs/jquery-plugin/jquery.slimscroll.min.js"></script>
<%-- selectize --%>
<link rel="stylesheet" href="${ctx}/static/libs/selectize/css/selectize.bootstrap3.css">
<script type="text/javascript" src="${ctx}/static/libs/selectize/js/standalone/selectize.js"></script>
<%-- ztree --%>
<link rel="stylesheet" href="${ctx}/static/libs/ztree/css/zTreeStyle/zTreeStyle.css">
<script type="text/javascript" src="${ctx}/static/libs/ztree/js/jquery.ztree.all.min.js"></script>
<script type="text/javascript" src="${ctx}/static/libs/ztree/js/jquery.ztree.exhide.min.js"></script>
<%-- kindeditor --%>
<link rel="stylesheet" href="${ctx}/static/libs/kindeditor/themes/default/default.css"/>
<script type="text/javascript" src="${ctx}/static/libs/kindeditor/kindeditor.js"></script>
<script type="text/javascript" src="${ctx}/static/libs/kindeditor/lang/zh-CN.js"></script>
<%-- jquery-file-upload --%>
<link rel="stylesheet" href="${ctx}/static/libs/jquery-file-upload/css/jquery.fileupload.css"/>
<script type="text/javascript" src="${ctx}/static/libs/jquery-file-upload/js/vendor/jquery.ui.widget.js"></script>
<script type="text/javascript" src="${ctx}/static/libs/jquery-file-upload/js/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="${ctx}/static/libs/jquery-file-upload/js/jquery.fileupload.js"></script>
<%-- bootstrap-slider --%>
<link rel="stylesheet" href="${ctx}/static/libs/bootstrap-slider/css/bootstrap-slider.css"/>
<script type="text/javascript" src="${ctx}/static/libs/bootstrap-slider/bootstrap-slider.js"></script>
<%-- moment --%>
<script type="text/javascript" src="${ctx}/static/libs/moment/moment.js"></script>
<script type="text/javascript" src="${ctx}/static/libs/moment/locale/zh-cn.js"></script>
<%-- Layer & Ext --%>
<script type="text/javascript" src="${ctx}/static/libs/layer/layer.js"></script>
<script type="text/javascript" src="${ctx}/static/js/plugins/jquery.layer.ext.js"></script>
<%-- validate --%>
<script type="text/javascript" src="${ctx}/static/libs/jquery-plugin/jquery.validate.js"></script>
<script type="text/javascript" src="${ctx}/static/js/plugins/jquery.validate.ext.js"></script>
<%-- bootstrap-datepicker --%>
<link rel="stylesheet" href="${ctx}/static/libs/eonasdan-bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css"/>
<script type="text/javascript" src="${ctx}/static/libs/eonasdan-bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="${ctx}/static/js/plugins/jquery.datepicker.js"></script>
<%-- 表格 --%>
<script type="text/javascript" src="${ctx}/static/js/plugins/jquery.datatable.js"></script>
<%-- 编辑器 --%>
<script type="text/javascript" src="${ctx}/static/js/plugins/jquery.editor.js"></script>
<%-- 树 --%>
<script type="text/javascript" src="${ctx}/static/js/plugins/jquery.tree.js"></script>
<%-- 附件插件 --%>
<script type="text/javascript" src="${ctx}/static/js/plugins/jquery.attachment.js"></script>
<%-- 模板 --%>
<script type="text/javascript" src="${ctx}/static/js/plugins/jquery.tpls.js"></script>